### ISSUE TITLE
Issue: No traces showing up in LangSmith

### ISSUE THREAD

**Issue by selvaradov** [langchain-ai/langsmith-sdk#1002]
### Issue you'd like to raise.

I'm trying to trace with LangSmith but it's not working correctly. I'm following the basic quickstart instructions, with the following code:
```python
import getpass
import os

os.environ["OPENAI_API_KEY"] = getpass.getpass("OpenAI API Key:")

os.environ["LANGCHAIN_TRACING_V2"] = "true"
os.environ["LANGCHAIN_API_KEY"] = getpass.getpass("LangSmith API Key:")
os.environ["LANGCHAIN_ENDPOINT"] = "https://api.smith.langchain.com"

from langchain_openai import ChatOpenAI

llm = ChatOpenAI()
llm.invoke("Hello, world!")
```

The completion comes through fine, but nothing shows up in the dashboard. When I run

```python
from langsmith import Client

client = Client()

url = next(client.list_runs(project_name="default")).url
print(url)
```
I get back a URL from one sample trace which was a few days ago, but no new traces are appearing even when I keep re-running the LLM. What might the cause be? I have tried switching out the API key for a new one but that didn't help.

**Comment by selvaradov** [comment]
This was solved by restarting the Jupyter environment things were running in - I don't know why it wasn't working earlier though.

**Comment by hinthornw** [comment]
We cache environment to reduce the frequency of checking os and reduce overhead.

It's likely that there was some langchain code executed before setting the environment here that made it so traces weren't sent.

In general, environment is meant to be set *before* executing a program rather than dynamically changed or treated as global state
