### ISSUE TITLE
Issue: Test Compare has inaccurate aggregated results

### ISSUE THREAD

**Issue by chasemcdo** [langchain-ai/langsmith-sdk#318]
### Issue you'd like to raise.

When you select results from your tests tables and compare them the aggregated results at the bottom can be in a different order than the actually displayed outputs.
![image](https://github.com/langchain-ai/langsmith-sdk/assets/74692158/59baab59-6ee0-4ae2-9dc1-52b2c783bfef)
![image](https://github.com/langchain-ai/langsmith-sdk/assets/74692158/a524a320-7e4b-4ecf-8989-092d5812549f)

You'll note that in these pictures I clicked ZS, FS, COT in that order, so we see the headers and results columns of the compare view display that.

But at the very bottom the aggregated results are shown in sorted creation order of COT, FS, ZS

### Suggestion:

It looks like it has to due with the aggregated results at the bottom being sorted by creation date, while the result display is based on the order you clicked them in.

Suggestion would be to remove the sort applied to the aggregated results in the compare test view.

**Comment by hinthornw** [comment]
Thanks for your patience, @chasemcdo ! That's a pretty frustrating bug! We'll fix this as soon as possible and get a change out in our next prod release. 

We are also going to revamp this page since it's honestly difficult to navigate once you have more than a couple of metrics in place. If you have specific ways you'd like to analyze the results that isn't well supported by the current UI, feel free to voice them here!
