### ISSUE TITLE
Issue: Getting random "Failed to batch ingest runs: LangSmithError('Failed to post https://api.smith.langchain.com/runs/batch in LangSmith API. HTTPError(\'422 Client Error: unknown for url: https://api.smith.langchain.com/runs/batch\', \'{"detail":"..." is longer than 128 characters"}\')')

### ISSUE THREAD

**Issue by ldorigo** [langchain-ai/langsmith-sdk#462]
### Issue you'd like to raise.

I started having these errors from langsmith when using it to trace langgraph runs. It ran fine until a couple of days ago.

Error message:

```
Failed to batch ingest runs: LangSmithError('Failed to post https://api.smith.langchain.com/runs/batch in LangSmith API. HTTPError('422 Client Error: unknown for url: [https://api.smith.langchain.com/runs/batch](https://api.smith.langchain.com/runs/batch/)', '{"detail":"[\'post\', \'items\', \'properties\', \'name\', \'maxLength\']: \\"ChannelRead<[\'raw_conversation\', \'messages\', \'query\', \'assistant_id\', \'assistant_nickname\', \'user_name\', \'user_roles\', \'organization_name\']>\\" is longer than 128 characters"}')')
```

**Comment by hinthornw** [comment]
Thanks for raising - we will work on a fix

**Comment by hinthornw** [comment]
Fix is in the pipeline - should go out later today/tomrrow

**Comment by hinthornw** [comment]
Fix should be deployed in prod now. LMK if you hit this again

**Comment by dds-normous** [comment]
Hi,
I am having this issue also.  
Here is some of the terminal results (which repeats every 180 seconds).

# Checking for new emails
Failed to batch ingest runs: LangSmithError("Failed to post .../runs/batch in LangSmith API. Invalid URL '.../runs/batch': No scheme supplied. Perhaps you meant https://.../runs/batch?\n")
## No new emails
## Waiting for 180 seconds
Failed to batch ingest runs: LangSmithError("Failed to post .../runs/batch in LangSmith API. Invalid URL '.../runs/batch': No scheme supplied. Perhaps you meant https://.../runs/batch?\n")

I had chatgpt check the .py files of the application, and it can't locate the possible URL issue.
It's response was: 

Understanding the Error
Invalid URL: The program is trying to make a web request to an API endpoint, but the URL it's using is incomplete or malformed because it lacks the scheme (http:// or https://).
LangSmithError: This is a custom error, likely defined in your CrewAI application or a dependency, indicating an issue specifically with LangSmith API interactions.
Suggested Fix: The error message even hints at a possible solution: ensuring the URL starts with https://.

Thanks for your help!
