### ISSUE TITLE
Issue: `@traceable` decorator breaks typing

### ISSUE THREAD

**Issue by fekstr** [langchain-ai/langsmith-sdk#551]
### Issue you'd like to raise.

I'm running into two typing issues when adding the `@traceable` decorator to functions.

`langsmith` version: 0.0.92

## 1. mypy doesn't validate parameters

```py
from langsmith import traceable


@traceable(name="fn")
def fn(param: str) -> str:
    return param


fn(not_param=0)

# mypy output: no issues found
# expected: Unexpected keyword argument "not_param" for "fn"
```

## 2. Generic return values don't resolve to the correct type

```py
from typing import TypeVar

from langsmith import traceable

T = TypeVar("T")


@traceable(name="fn")
def fn(param: T) -> T:
    return param


val = fn(param=0)

a: str = val

# mypy output: no issues found
# expected: Incompatible types in assignment (expression has type "int", variable has type "str")
```

### Suggestion:

See expected outputs above.

**Comment by hinthornw** [comment]
Ack

**Comment by hinthornw** [comment]
Made some improvements a while back. Gonna close for now but feel free to re-open if you have a better recommendation

**Comment by blast-hardcheese** [comment]
Hello! I mentioned this issue over here: https://discuss.python.org/t/extract-kwargs-types-from-a-function-signature/34238/11

I ran into an issue where both pyright and mypy failed to catch downstream errors due to the illegal position of `langsmith_extra` in `SupportsLangsmithExtra`:

> `error: Keyword parameter "langsmith_extra" cannot appear in signature after ParamSpec args parameter (reportGeneralTypeIssues)`

As you have no doubt been wrestling with, the [documentation for `typing`](https://typing.readthedocs.io/en/latest/spec/generics.html#id5) includes:

> Placing keyword-only parameters between the *args and **kwargs is forbidden.

The PEP goes [into more detail](https://peps.python.org/pep-0612/#concatenating-keyword-parameters), but the end result is the same.

A minimal reproducing case of the issue showing that both mypy and pyright fail to detect the issue is included at the end of this post.

Note, the `pyright: ignore` was necessary to get beyond `Keyword parameter "langsmith_extra" cannot appear in signature after ParamSpec args parameter` mentioned above, but this has the unfortunate effect of halting that whole branch of pyright's check, resulting in failing to catch the structural issue at `foo`'s invocation point.

_interestingly,_ pyright _does_ see the type correctly when using `reveal_type(foo)`:

```
Type of "foo" is "SupportsLangsmithExtra[(x: int, /, *, b: bool), None]" (Pyright)
```

... but it still fails to check.

---

```python
import functools
from typing import Any, Callable, Optional, ParamSpec, TypeVar
from langsmith.run_helpers import LangSmithExtra, SupportsLangsmithExtra


Param = ParamSpec("Param")
RetType = TypeVar("RetType")

def track(
    func: Callable[Param, RetType],
) -> SupportsLangsmithExtra[Param, RetType]:
    @functools.wraps(func)
    def wrapper(
        *func_args: Param.args,
        langsmith_extra: Optional[LangSmithExtra] = None,  # pyright: ignore
        **func_kwargs: Param.kwargs,
    ) -> Any:
        return "irrelevant"

    return wrapper

@track
def foo(x: int, /, *, b: bool) -> None:
    pass


foo()  # Does not flag missing parameters
```
