### ISSUE TITLE
Issue: Langsmith thread UI is empty

### ISSUE THREAD

**Issue by JustinLeeGrab** [langchain-ai/langsmith-sdk#926]
### Issue you'd like to raise.

Hi, I have multiple runs (traces) that belong to the same thread. Each trace is valid - contains all the LLM & tools information (Screenshot 1). But when I click the thread, nothing seems to be there (Screenshot 2). 

This is consistently replicable. This only happens when I invoke the langgraph from my **streamlit** app, but when I use _postman_ to directly invoke the langgraph then there is _no issue._ 

**Screenshot 1: Valid Trace**
<img width="1040" alt="Screenshot 2024-08-16 at 2 50 51 PM" src="https://github.com/user-attachments/assets/d558ecc8-6a92-47e0-b128-0602b66814e4">

**Screenshot 2: Empty thread** 
<img width="1658" alt="Screenshot 2024-08-16 at 2 51 36 PM" src="https://github.com/user-attachments/assets/03cb33dc-abfb-43f1-ba2f-f3c6e2061cef">

**Screenshot 3: UI shows that the thread contains traces**
<img width="1315" alt="Screenshot 2024-08-16 at 2 52 01 PM" src="https://github.com/user-attachments/assets/22855615-54d3-4981-b24f-25b020ba976e">

Please help, thank you very much in advance

**Comment by hinthornw** [comment]
So just to clarify to make sure I understand, the issue is that the threadUI view is empty despite having the row in the "threads" tab show that 2 traces are within that thread?

Initially I though perhaps it's because the thread_id needs to be in `metadata` not in `inputs`, but if ^^ is true then I'd assume it's in the metadata as well, but the metadata isn't shown in any of the screenshots.

Will flag to the team

**Comment by hinthornw** [comment]
Closing as stale - feel free to re-open
